n_500_p_20:
  num_grids_height: 20
  num_grids_width: 20

  train_size: 0.7
  val_size: 0.1
  
  lr: 0.001
  weight_decay: 0
  milestones: [50]
  clip_grad: 0
  batch_size: 32
  max_epochs: 200

  pass_device: True

  model_args:
    num_grids_height: 20
    num_grids_width: 20
    input_dim: 3
    output_dim: 1
    hidden_dim: 32
    grid_embedding_dim: 16
    cheb_k: 3
    num_layers: 3

n_2500_p_20:
  num_grids_height: 20
  num_grids_width: 20

  train_size: 0.7
  val_size: 0.1
  
  lr: 0.001
  weight_decay: 0
  milestones: [50]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  pass_device: True

  model_args:
    num_grids_height: 20
    num_grids_width: 20
    input_dim: 3
    output_dim: 1
    hidden_dim: 32
    grid_embedding_dim: 16
    cheb_k: 3
    num_layers: 3
