n_20_p_10:
  num_grids_width: 20
  num_grids_height: 20

  train_size: 0.7
  val_size: 0.1
  
  lr: 0.001
  weight_decay: 0
  milestones: [10, 20]
  clip_grad: 0
  batch_size: 16
  max_epochs: 200

  model_args:
    num_grids_width: 20
    num_grids_height: 20
    input_dim: 2
    output_dim: 1
